services:
  postgres:
    image: postgres:16-alpine
    container_name: motomedic-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: motomedic
      POSTGRES_PASSWORD: motomedic
      POSTGRES_DB: motomedic
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
